### ISSUE TITLE
novi order nakon submit; sensor blackout

### ISSUE THREAD

**Issue by karajfilip** [karajfilip/ariac22#3]
-> treba pricekati order prije zatvaranja natjecanja
-> implementirat pusnikovu ideju za blackout

**Comment by marijapili** [comment]
treba pricekati order prije zatvaranja natjecanja - RIJESENO, sleep(5) pa jos jednom provjeri ima li cega i tek onda kraj

**Comment by marijapili** [comment]
sensor blackout spojiti s high levelom
